name: Build ESP32-S3 Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install platformio esptool

      - name: Build
        run: pio run

      - name: Merge Factory Firmware
        run: |
          python -m esptool --chip esp32s3 merge_bin \
            -o .pio/build/esp32-s3-devkitc-1/firmware-factory.bin \
            --flash_mode dio \
            --flash_size 16MB \
            0x0 .pio/build/esp32-s3-devkitc-1/bootloader.bin \
            0x8000 .pio/build/esp32-s3-devkitc-1/partitions.bin \
            0x10000 .pio/build/esp32-s3-devkitc-1/firmware.bin

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/esp32-s3-devkitc-1/firmware-factory.bin
